-- File sinh tự động bởi scripts/generate-seed.mts — không sửa tay.
begin;

-- Nhóm sản phẩm
insert into public.product_groups (id, category, title, description, sort_order) values ('banh-kem-sinh-nhat', 'Bánh', 'Bánh Kem & Bánh Ổ', 'Cốt bánh mềm ẩm, kem tươi thanh nhẹ ít ngọt chuẩn vị châu Âu', 0) on conflict (id) do nothing;
insert into public.product_groups (id, category, title, description, sort_order) values ('banh-ngot-trang-mieng', 'Bánh', 'Bánh Ngọt & Tráng Miệng', 'Những món ngọt nhỏ xinh hoàn hảo để thưởng thức cùng tách trà ấm', 1) on conflict (id) do nothing;
insert into public.product_groups (id, category, title, description, sort_order) values ('banh-nuong-croissant', 'Bánh', 'Bánh Nướng & Croissant', 'Nướng tươi mỗi sớm, thơm giòn ngập tràn hương bơ Pháp hảo hạng', 2) on conflict (id) do nothing;
insert into public.product_groups (id, category, title, description, sort_order) values ('tra-trai-cay-tra-sua', 'Đồ uống', 'Trà Trái Cây & Trà Sữa', 'Đậm vị trà mộc tự nhiên, hoa quả tươi theo mùa thanh mát sảng khoái', 3) on conflict (id) do nothing;
insert into public.product_groups (id, category, title, description, sort_order) values ('ca-phe-thu-cong-latte', 'Đồ uống', 'Cà Phê Thủ Công & Latte', 'Hạt cà phê Arabica Cầu Đất phối trộn Robusta rang mộc đậm đà', 4) on conflict (id) do nothing;
insert into public.product_groups (id, category, title, description, sort_order) values ('nuoc-ep-da-xay', 'Đồ uống', 'Nước Ép & Đá Xay', 'Thức uống tươi mát giàu vitamin cho ngày thêm hứng khởi và năng lượng', 5) on conflict (id) do nothing;

-- Sản phẩm
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (101, 'banh-bong-lan-mat-ong', 'Bánh Bông Lan Mật Ong', 'Bánh', 'banh-kem-sinh-nhat', 'Bông lan mềm xốp quyện cùng mật ong hoa nhãn thơm lừng', 185000, null, 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80', '#1 Best-seller', 5, 142, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (102, 'matcha-roll-cake', 'Matcha Roll Cake', 'Bánh', 'banh-kem-sinh-nhat', 'Trà xanh Uji Nhật Bản đậm vị kết hợp cùng lớp kem tươi mịn màng', 220000, null, 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=600&auto=format&fit=crop&q=80', 'Trending', 5, 77, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (103, 'banh-red-velvet', 'Red Velvet Cream Cheese', 'Bánh', 'banh-kem-sinh-nhat', 'Sắc đỏ nhung quyến rũ xen kẽ lớp phô mai kem chua ngọt hài hoà', 85000, 95000, 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?w=600&auto=format&fit=crop&q=80', 'Sale', 5, 68, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (104, 'eclair-ca-phe-so-co-la', 'Éclair Cà Phê & Sô Cô La', 'Bánh', 'banh-ngot-trang-mieng', 'Vỏ bánh su dài truyền thống Pháp ngập tràn nhân kem cà phê đậm đà', 65000, 75000, 'https://images.unsplash.com/photo-1612203985729-70726954388c?w=600&auto=format&fit=crop&q=80', 'Yêu thích', 5, 98, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (105, 'banh-su-kem-vanilla', 'Bánh Su Kem Vanilla Bourbon', 'Bánh', 'banh-ngot-trang-mieng', 'Nhân kem custard từ hạt vani Bourbon thơm nồng nàn', 28000, null, 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80', null, 5, 89, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (106, 'tiramisu-ca-ly', 'Tiramisu Cá Ly Truyền Thống', 'Bánh', 'banh-ngot-trang-mieng', 'Hương vị Ý nguyên bản với bánh sampa đẫm cà phê và phô mai mascarpone', 75000, null, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80', 'Top Pick', 5, 95, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (107, 'croissant-bo-phap', 'Croissant Bơ Pháp Cổ Điển', 'Bánh', 'banh-nuong-croissant', 'Hàng trăm lớp bột giòn xốp thơm lừng bơ Pháp AOP cao cấp', 45000, null, 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80', 'Mới', 5, 33, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (108, 'tart-trung-hong-kong', 'Tart Trứng Hồng Kông', 'Bánh', 'banh-nuong-croissant', 'Lớp vỏ ngàn lớp giòn tan bao bọc nhân trứng béo ngậy mềm mịn', 35000, null, 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=600&auto=format&fit=crop&q=80', null, 4, 61, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (109, 'banh-sua-chua-chanh-leo', 'Bánh Sữa Chua Chanh Leo', 'Bánh', 'banh-nuong-croissant', 'Chua ngọt thanh mát, vị chanh leo tự nhiên giúp giải ngấy tuyệt vời', 175000, null, 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&auto=format&fit=crop&q=80', null, 5, 54, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (201, 'tra-sua-tran-chau-cari', 'Trà Sữa Trân Châu Cari', 'Đồ uống', 'tra-trai-cay-tra-sua', 'Trà đen nguyên bản pha sữa béo ngậy cùng trân châu hoàng kim dẻo bùi', 55000, null, 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=600&auto=format&fit=crop&q=80', 'Hot', 5, 112, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (202, 'tra-dao-cam-sa', 'Trà Đào Cam Sả Tươi', 'Đồ uống', 'tra-trai-cay-tra-sua', 'Hương thơm nồng nàn của sả cây, cam vàng mọng nước và miếng đào giòn ngọt', 45000, null, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80', 'Mới', 5, 45, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (203, 'tra-dau-tay-hoa-hong', 'Trà Dâu Tây Hoa Hồng', 'Đồ uống', 'tra-trai-cay-tra-sua', 'Vị ngọt dịu thơm hương hoa hồng kết hợp mứt dâu tây Đà Lạt tự nấu', 50000, 58000, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&auto=format&fit=crop&q=80', 'Best-seller', 5, 82, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (204, 'ca-phe-sua-da-cari', 'Cà Phê Sữa Đá Cari', 'Đồ uống', 'ca-phe-thu-cong-latte', 'Hương vị cà phê truyền thống Việt Nam đậm đặc, sánh mịn béo ngọt', 45000, null, 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80', null, 5, 64, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (205, 'latte-hat-de', 'Latte Hạt Dẻ Béo Ngậy', 'Đồ uống', 'ca-phe-thu-cong-latte', 'Espresso thơm nhẹ hòa quyện sữa tươi đánh bọt mịn và siro hạt dẻ nướng', 55000, null, 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=600&auto=format&fit=crop&q=80', 'Yêu thích', 5, 48, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (206, 'ca-phe-muoi-kem-beo', 'Cà Phê Muối Kem Béo', 'Đồ uống', 'ca-phe-thu-cong-latte', 'Lớp kem mặn béo ngậy độc đáo nâng tầm hương vị cà phê phin đậm chất', 48000, null, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80', 'Trending', 5, 91, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (207, 'nuoc-ep-cam-tao-tuoi', 'Nước Ép Cam Táo Tươi', 'Đồ uống', 'nuoc-ep-da-xay', '100% trái cây tươi ép chậm nguyên chất, không thêm đường hoá học', 50000, null, 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80', null, 5, 39, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (208, 'matcha-da-xay-kem', 'Matcha Đá Xay Kem Tươi', 'Đồ uống', 'nuoc-ep-da-xay', 'Bột trà xanh Nhật xay nhuyễn mịn với sữa tươi và chỏm kem bông xốp', 60000, null, 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80', 'Đặc biệt', 5, 73, null, 20, 'active') on conflict (id) do nothing;
insert into public.products (id, slug, name, category, subcategory, description, price, original_price, image, badge, rating, reviews, sizes, stock, status) values (209, 'chocolate-freeze-hanh-nhan', 'Chocolate Freeze Hạnh Nhân', 'Đồ uống', 'nuoc-ep-da-xay', 'Sô cô la Bỉ nguyên chất đậm đà rắc hạnh nhân lát nướng giòn rụm', 60000, null, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80', null, 5, 56, null, 20, 'active') on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.products', 'id'), (select coalesce(max(id), 1) from public.products));

-- Đánh giá
insert into public.reviews (id, name, avatar, rating, date, content) values (1, 'Nguyễn Minh Thư', 'https://placehold.co/80x80/F6CE8B/1B4B5A?text=MT', 5, '15/09/2026', 'Bánh ngon thật sự! Mình đặt bánh sinh nhật cho mẹ, team Cari tư vấn rất tận tình và bánh ra lò đúng như ý. Kem không quá ngọt, bánh bông xốp. Chắc chắn sẽ quay lại!') on conflict (id) do nothing;
insert into public.reviews (id, name, avatar, rating, date, content) values (2, 'Trần Hoàng Nam', 'https://placehold.co/80x80/1B4B5A/FCE9C6?text=HN', 5, '02/09/2026', 'Croissant bơ Pháp ở đây đỉnh lắm, lớp vỏ giòn rụm mà bên trong mềm thơm. Giao hàng nhanh, đóng gói cẩn thận. Mua lần đầu dùng mã CARI10 được giảm ngay, rất thích!') on conflict (id) do nothing;
insert into public.reviews (id, name, avatar, rating, date, content) values (3, 'Lê Bảo Châu', 'https://placehold.co/80x80/C97B3D/FFF8EF?text=BC', 5, '28/08/2026', 'Không gian ảo nhưng chất lượng thật. Tiramisu cá ly của Cari là ngon nhất mình từng ăn ở Hà Nội. Hương cà phê đậm đà, kem mascarpone mịn. Đặt hàng online siêu tiện.') on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.reviews', 'id'), (select coalesce(max(id), 1) from public.reviews));

-- Nội dung trang & cài đặt
insert into public.site_content (key, value) values ('home', '{"heroSlides":[{"id":1,"image":"https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1920&auto=format&fit=crop&q=80","title":"Bánh tươi thơm từ lò","ctaLabel":"Khám phá ngay","ctaHref":"/san-pham","showText":false},{"id":2,"image":"https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1920&auto=format&fit=crop&q=80","title":"Bánh đặt theo yêu cầu","ctaLabel":"Đặt bánh ngay","ctaHref":"/dat-theo-yeu-cau","showText":false},{"id":3,"image":"https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=1920&auto=format&fit=crop&q=80","title":"Giảm 10% đơn đầu tiên","ctaLabel":"Mua ngay","ctaHref":"/san-pham","showText":false}],"features":[{"id":"points","title":"Chương trình tích điểm"},{"id":"delivery","title":"Giao hàng tận nơi"},{"id":"preorder","title":"Đặt trước"}],"banners":[{"label":"Bánh","href":"/san-pham?danh-muc=banh","image":"https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&auto=format&fit=crop&q=80"},{"label":"Đồ uống","href":"/san-pham?danh-muc=do-uong","image":"https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80"}],"topOrderSlugs":["banh-bong-lan-mat-ong","eclair-ca-phe-so-co-la","matcha-roll-cake"],"menuSlugs":["banh-sua-chua-chanh-leo","croissant-bo-phap","tart-trung-hong-kong","banh-su-kem-vanilla","tra-sua-tran-chau-cari","ca-phe-sua-da-cari","banh-red-velvet","tiramisu-ca-ly"],"gallery":[{"id":1,"image":"https://placehold.co/600x600/F6CE8B/1B4B5A?text=Gallery+1","alt":"Không gian cửa hàng Cari Bakehouse"},{"id":2,"image":"https://placehold.co/600x600/1B4B5A/FFF8EF?text=Gallery+2","alt":"Bánh tươi mỗi ngày"},{"id":3,"image":"https://placehold.co/600x600/C97B3D/FFF8EF?text=Gallery+3","alt":"Eclair sô cô la thơm lừng"},{"id":4,"image":"https://placehold.co/600x600/123640/FCE9C6?text=Gallery+4","alt":"Quầy bánh Cari"},{"id":5,"image":"https://placehold.co/600x600/FCE9C6/1B4B5A?text=Gallery+5","alt":"Bếp làm bánh thủ công"},{"id":6,"image":"https://placehold.co/600x600/E5D9C3/1B4B5A?text=Gallery+6","alt":"Đóng gói bánh tặng quà"}],"about":{"image":"https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=900&auto=format&fit=crop&q=80","badge":"Tiệm bánh thủ công từ 2024","quote":"Cari bắt đầu từ một tình yêu rất đơn giản: thích làm bánh và thích nhìn mọi người ăn bánh mình làm. Tụi mình làm bánh với mong muốn mang đến những món ngọt thật dễ thương, thật ngon và đủ gần gũi để bạn có thể ghé Cari bất cứ khi nào muốn tự thưởng cho mình một chút ngọt ngào."},"featuredReviewIds":[1,2,3]}'::jsonb) on conflict (key) do nothing;
insert into public.site_content (key, value) values ('about', '{"storyBadge":"Câu chuyện của Cari","storyTitle":"Vun vén ngọt ngào từ những điều giản dị","storyBody":"Cari bắt đầu từ một tình yêu rất đơn giản: thích làm bánh và thích nhìn mọi người ăn bánh mình làm. Tụi mình làm bánh với mong muốn mang đến những món ngọt thật dễ thương, thật ngon và đủ gần gũi để bạn có thể ghé Cari bất cứ khi nào muốn tự thưởng cho mình một chút ngọt ngào.","values":[{"icon":"shield","title":"Nguyên liệu chất lượng","desc":"Ưu tiên nguyên liệu sạch và an toàn cho từng chiếc bánh"},{"icon":"heart","title":"Chăm chút từng bước nhỏ","desc":"Từ khâu chọn nguyên liệu đến hoàn thiện, đều được làm cẩn thận"},{"icon":"clock","title":"Làm mới mỗi ngày","desc":"Bánh được sản xuất tươi theo đơn hàng ngày"},{"icon":"calendar","title":"Đồng hành mọi khoảnh khắc","desc":"Từ một miếng bánh sau bữa ăn đến một chiếc bánh sinh nhật, Cari. luôn ở đó"}],"faq":[{"question":"Cari Bakehouse giao hàng khu vực nào?","answer":"Giao hàng tận nơi trong toàn khu vực Hà Nội, thời gian giao cụ thể sẽ được thông báo khi xác nhận đơn."},{"question":"Phí giao hàng tính như thế nào?","answer":"Với đơn đặt qua các nền tảng như Shopeefood, Grabfood, phí ship tính theo chính sách nền tảng đó. Với đơn đặt trực tiếp ngoài nền tảng, phí ship tính theo ứng dụng Aha."},{"question":"Bánh lớn/đặt theo yêu cầu cần đặt trước bao lâu?","answer":"Đặt trước tối thiểu 12 tiếng đối với bánh kích thước lớn, và cần thanh toán trước khi tiệm bắt đầu làm bánh. Đơn xác nhận sau khi hai bên thống nhất thiết kế, số lượng và đặt cọc (nếu có)."},{"question":"Có cần đặt cọc khi mua bánh không?","answer":"Bánh thường (sản xuất hàng ngày) không yêu cầu đặt cọc. Với bánh đặc biệt/đặt riêng, tiệm yêu cầu cọc trước 100% giá trị đơn."},{"question":"Cari Bakehouse có nhận đổi/trả bánh không?","answer":"Tiệm không nhận đổi/trả nếu khách đổi ý sau khi đã xác nhận đơn. Chỉ hỗ trợ đổi/trả/hoàn tiền khi giao sai bánh, bánh bị hư hỏng do vận chuyển, hoặc lỗi chất lượng từ khâu sản xuất. Khách cần gửi khiếu nại kèm ảnh chụp trong vòng 2-4 tiếng sau khi nhận hàng, tiệm phản hồi trong vòng 24 giờ."},{"question":"Thanh toán bằng cách nào?","answer":"Chuyển khoản, tiền mặt khi nhận hàng (COD tại khu vực hỗ trợ), hoặc thanh toán trực tiếp tại cửa hàng."}]}'::jsonb) on conflict (key) do nothing;
insert into public.site_content (key, value) values ('settings', '{"hotline":"0338975925","email":"cari.bakehouse07@gmail.com","zalo":"https://zalo.me/0338975925","instagram":"https://www.instagram.com/cari.bakehouse.hn/","facebook":"","tiktok":"","threads":"https://www.threads.com/@cari.bakehouse.hn"}'::jsonb) on conflict (key) do nothing;
insert into public.site_content (key, value) values ('products_page', '{"categoryPickerLabel":"Chọn danh mục"}'::jsonb) on conflict (key) do nothing;

commit;
