-- ============================================================
--  Cari Bakehouse — cấu trúc database ban đầu (Giai đoạn 4)
--  Cách chạy: Supabase Dashboard → SQL Editor → New query → dán toàn bộ file → Run.
--  Bám sát kiểu dữ liệu trong src/types/* và src/lib/mock-data.ts.
-- ============================================================

-- Ngày hiện tại theo giờ Việt Nam (server Supabase chạy giờ UTC)
create or replace function public.today_vn()
returns date
language sql stable
as $$ select (now() at time zone 'Asia/Ho_Chi_Minh')::date; $$;

-- Lệnh đến từ website (khách vãng lai hoặc người đã đăng nhập)? Chạy trong SQL Editor thì trả về false.
create or replace function public.from_website()
returns boolean
language sql stable
as $$ select coalesce(auth.jwt() ->> 'role', '') in ('anon', 'authenticated'); $$;

-- ─── Hồ sơ người dùng đăng nhập (1-1 với auth.users) ─────────
create table public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text not null default '',
  phone       text not null default '',
  role        text not null default 'customer' check (role in ('customer', 'admin')),
  created_at  timestamptz not null default now()
);

-- Kiểm tra người đang gọi có phải admin không (security definer để tránh vòng lặp RLS)
create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- Email của người đang đăng nhập (chữ thường), dùng để khớp đơn hàng / điểm theo email
create or replace function public.current_email()
returns text
language sql stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

-- ─── Khách hàng (khóa theo email, như dữ liệu mẫu) ───────────
create sequence public.customer_code_seq;

create table public.customers (
  id          text primary key default 'KH' || lpad(nextval('public.customer_code_seq')::text, 3, '0'),
  user_id     uuid unique references auth.users (id) on delete set null,
  full_name   text not null,
  email       text not null,
  phone       text not null default '',
  created_at  date not null default public.today_vn()
);
create unique index customers_email_key on public.customers (lower(email));

-- Tạo hồ sơ khách nếu email chưa có (dùng trong trigger, chạy với quyền hệ thống)
create or replace function public.ensure_customer(p_full_name text, p_email text, p_phone text, p_user_id uuid default null)
returns void
language plpgsql security definer set search_path = ''
as $$
begin
  if coalesce(trim(p_email), '') = '' then
    return;
  end if;
  insert into public.customers (full_name, email, phone, user_id)
  values (coalesce(nullif(trim(p_full_name), ''), trim(p_email)), trim(p_email), coalesce(trim(p_phone), ''), p_user_id)
  on conflict ((lower(email))) do update
    set user_id = coalesce(public.customers.user_id, excluded.user_id);
end;
$$;

-- Khi có người đăng ký tài khoản: tạo profile + hồ sơ khách
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), coalesce(new.raw_user_meta_data ->> 'phone', ''));

  perform public.ensure_customer(
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    new.email,
    new.raw_user_meta_data ->> 'phone',
    new.id
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─── Nhóm sản phẩm & sản phẩm ────────────────────────────────
create table public.product_groups (
  id          text primary key,
  category    text not null check (category in ('Bánh', 'Đồ uống')),
  title       text not null,
  description text not null default '',
  sort_order  int  not null default 0
);

create table public.products (
  id              bigint generated by default as identity primary key,
  slug            text not null unique,
  name            text not null,
  category        text not null,
  -- id nhóm (product_groups.id); không cho xóa nhóm còn sản phẩm
  subcategory     text references public.product_groups (id) on update cascade on delete restrict,
  description     text,
  price           int  not null check (price >= 0),
  original_price  int  check (original_price >= 0),
  image           text not null default '',
  badge           text,
  rating          numeric(2, 1) not null default 5,
  reviews         int  not null default 0,
  -- [{ "label": "16cm", "price": 350000 }, ...]
  sizes           jsonb,
  stock           int,
  status          text not null default 'active' check (status in ('active', 'soldout', 'hidden')),
  created_at      timestamptz not null default now()
);

-- ─── Đánh giá ────────────────────────────────────────────────
create table public.reviews (
  id       bigint generated by default as identity primary key,
  name     text not null,
  avatar   text not null default '',
  rating   int  not null check (rating between 1 and 5),
  date     text not null,
  content  text not null
);

-- ─── Nội dung trang & cài đặt (mỗi khóa là 1 object JSON) ─────
--  key: 'home' | 'about' | 'settings' | 'products_page'
create table public.site_content (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now()
);

-- ─── Đơn hàng ────────────────────────────────────────────────
-- Mã đơn dạng #CB1234, không trùng
create or replace function public.generate_order_id()
returns text
language plpgsql
as $$
declare
  new_id text;
begin
  loop
    new_id := '#CB' || (1000 + floor(random() * 9000))::int;
    exit when not exists (select 1 from public.orders where id = new_id);
  end loop;
  return new_id;
end;
$$;

create table public.orders (
  id              text primary key,
  created_at      date not null default public.today_vn(),
  -- [{ "name": ..., "size": ..., "quantity": 1, "price": 350000 }, ...]
  items           jsonb not null,
  subtotal        int  not null check (subtotal >= 0),
  voucher_code    text,
  discount        int  not null default 0 check (discount >= 0),
  total           int  not null check (total >= 0),
  status          text not null default 'Chờ xử lý' check (status in ('Chờ xử lý', 'Đã giao', 'Đã hủy')),
  fulfillment     text not null check (fulfillment in ('delivery', 'pickup')),
  address         text,
  receive_date    date not null,
  receive_time    text not null,
  note            text,
  payment_method  text not null check (payment_method in ('cod', 'bank')),
  customer_name   text,
  customer_phone  text,
  customer_email  text,
  user_id         uuid references auth.users (id) on delete set null default auth.uid()
);
alter table public.orders alter column id set default public.generate_order_id();
create index orders_customer_email_idx on public.orders (lower(customer_email));

-- ─── Lịch sử điểm ────────────────────────────────────────────
create sequence public.point_code_seq;

create table public.point_logs (
  id        text primary key default 'P' || lpad(nextval('public.point_code_seq')::text, 3, '0'),
  email     text not null,
  date      date not null default public.today_vn(),
  title     text not null,
  points    int  not null check (points <> 0),
  kind      text not null check (kind in ('order', 'manual', 'redeem', 'initial')),
  order_id  text references public.orders (id) on delete set null,
  reason    text
);
create index point_logs_email_idx on public.point_logs (lower(email));
-- Mỗi đơn chỉ được cộng điểm 1 lần
create unique index point_logs_one_per_order on public.point_logs (order_id) where kind = 'order';

-- Quy tắc tích điểm: 1.000đ = 1 điểm
create or replace function public.points_for_order(p_total int)
returns int
language sql immutable
as $$ select floor(p_total / 1000.0)::int; $$;

-- ─── Bánh đặt theo yêu cầu ───────────────────────────────────
create sequence public.custom_request_code_seq;

create table public.custom_requests (
  id                text primary key default 'YC' || lpad(nextval('public.custom_request_code_seq')::text, 4, '0'),
  created_at        date not null default public.today_vn(),
  customer_name     text not null,
  phone             text not null,
  customer_email    text,
  occasion          text not null default '',
  delivery_date     date not null,
  size_guest_count  text not null default '',
  flavor            text not null default '',
  budget            text not null default '',
  notes             text not null default '',
  reference_image   text,
  status            text not null default 'Mới'
                    check (status in ('Mới', 'Đang tư vấn', 'Đã báo giá', 'Đã cọc', 'Hoàn tất', 'Đã hủy')),
  quoted_price      int check (quoted_price >= 0),
  user_id           uuid references auth.users (id) on delete set null default auth.uid()
);

-- ============================================================
--  Quy tắc nghiệp vụ chạy trong database (không thể lách từ trình duyệt)
-- ============================================================

-- Đơn mới: luôn "Chờ xử lý" và tạo hồ sơ khách theo email
create or replace function public.before_order_insert()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  if public.from_website() and not public.is_admin() then
    new.status := 'Chờ xử lý';
    new.created_at := public.today_vn();
    new.user_id := auth.uid();
  end if;
  perform public.ensure_customer(new.customer_name, new.customer_email, new.customer_phone, auth.uid());
  return new;
end;
$$;

create trigger orders_before_insert
  before insert on public.orders
  for each row execute function public.before_order_insert();

-- Đổi trạng thái đơn: chỉ Chờ xử lý → Đã giao / Đã hủy; Đã giao thì tự cộng điểm
create or replace function public.before_order_status_change()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  pts int;
begin
  if new.status is distinct from old.status then
    if old.status <> 'Chờ xử lý' then
      raise exception 'Đơn đã kết thúc, không thể đổi trạng thái';
    end if;

    pts := public.points_for_order(new.total);
    if new.status = 'Đã giao' and coalesce(new.customer_email, '') <> '' and pts > 0 then
      insert into public.point_logs (email, points, kind, order_id, title)
      values (new.customer_email, pts, 'order', new.id, 'Đơn hàng ' || new.id || ' hoàn tất')
      on conflict do nothing;
    end if;
  end if;
  return new;
end;
$$;

create trigger orders_status_change
  before update of status on public.orders
  for each row execute function public.before_order_status_change();

-- Yêu cầu đặt bánh mới: luôn "Mới", chưa có báo giá
create or replace function public.before_custom_request_insert()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  if public.from_website() and not public.is_admin() then
    new.status := 'Mới';
    new.quoted_price := null;
    new.created_at := public.today_vn();
    new.user_id := auth.uid();
  end if;
  return new;
end;
$$;

create trigger custom_requests_before_insert
  before insert on public.custom_requests
  for each row execute function public.before_custom_request_insert();

-- Admin cộng/trừ điểm thủ công: không cho số dư âm
create or replace function public.check_point_balance()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  balance int;
begin
  select coalesce(sum(points), 0) into balance
  from public.point_logs where lower(email) = lower(new.email);
  if balance + new.points < 0 then
    raise exception 'Không thể trừ quá số điểm hiện có (% điểm)', balance;
  end if;
  return new;
end;
$$;

create trigger point_logs_check_balance
  before insert on public.point_logs
  for each row execute function public.check_point_balance();

-- ============================================================
--  Bảo mật theo dòng (RLS)
-- ============================================================
alter table public.profiles        enable row level security;
alter table public.customers       enable row level security;
alter table public.product_groups  enable row level security;
alter table public.products        enable row level security;
alter table public.reviews         enable row level security;
alter table public.site_content    enable row level security;
alter table public.orders          enable row level security;
alter table public.point_logs      enable row level security;
alter table public.custom_requests enable row level security;

-- profiles: tự xem/sửa hồ sơ của mình (không tự đổi role), admin xem tất cả
create policy "profiles: xem của mình hoặc admin" on public.profiles
  for select using (id = auth.uid() or public.is_admin());
create policy "profiles: sửa của mình hoặc admin" on public.profiles
  for update using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());
-- Từ website chỉ sửa được tên + sđt; đổi role (cấp quyền admin) chỉ làm trong SQL Editor
revoke update on public.profiles from anon, authenticated;
grant update (full_name, phone) on public.profiles to authenticated;

-- customers: khách xem hồ sơ của mình, admin toàn quyền
create policy "customers: xem của mình hoặc admin" on public.customers
  for select using (lower(email) = public.current_email() or public.is_admin());
create policy "customers: admin ghi" on public.customers
  for all using (public.is_admin()) with check (public.is_admin());

-- Dữ liệu công khai: ai cũng đọc được, chỉ admin sửa
create policy "product_groups: ai cũng xem" on public.product_groups for select using (true);
create policy "product_groups: admin ghi" on public.product_groups
  for all using (public.is_admin()) with check (public.is_admin());

create policy "products: xem sản phẩm không ẩn" on public.products
  for select using (status <> 'hidden' or public.is_admin());
create policy "products: admin ghi" on public.products
  for all using (public.is_admin()) with check (public.is_admin());

create policy "reviews: ai cũng xem" on public.reviews for select using (true);
create policy "reviews: admin ghi" on public.reviews
  for all using (public.is_admin()) with check (public.is_admin());

create policy "site_content: ai cũng xem" on public.site_content for select using (true);
create policy "site_content: admin ghi" on public.site_content
  for all using (public.is_admin()) with check (public.is_admin());

-- orders: ai cũng đặt được (kể cả khách vãng lai); xem đơn của mình; chỉ admin đổi trạng thái
create policy "orders: đặt đơn" on public.orders for insert with check (true);
create policy "orders: xem của mình hoặc admin" on public.orders
  for select using (lower(customer_email) = public.current_email() or public.is_admin());
create policy "orders: admin sửa" on public.orders
  for update using (public.is_admin()) with check (public.is_admin());
create policy "orders: admin xóa" on public.orders for delete using (public.is_admin());

-- point_logs: khách xem điểm của mình; admin toàn quyền
create policy "point_logs: xem của mình hoặc admin" on public.point_logs
  for select using (lower(email) = public.current_email() or public.is_admin());
create policy "point_logs: admin ghi" on public.point_logs
  for all using (public.is_admin()) with check (public.is_admin());

-- custom_requests: ai cũng gửi được; xem của mình; admin cập nhật
create policy "custom_requests: gửi yêu cầu" on public.custom_requests for insert with check (true);
create policy "custom_requests: xem của mình hoặc admin" on public.custom_requests
  for select using (lower(customer_email) = public.current_email() or public.is_admin());
create policy "custom_requests: admin sửa" on public.custom_requests
  for update using (public.is_admin()) with check (public.is_admin());
create policy "custom_requests: admin xóa" on public.custom_requests for delete using (public.is_admin());
